version: "3.8"

services:
  talenta-attendance-bot:
    build: .
    env_file:
      - .env
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - amay_network

networks:
  amay_network:
    external: true